/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bureau.graph;

import java.util.*;
import javax.swing.JOptionPane;
import messages.metier.Bureau;
import bureau.DAO.BureauDAO;
import bureau.DAO.DAO;

/**
 *
 * @author USER
 */
public class creabur extends javax.swing.JPanel {

    /**
     * Creates new form CreaCli
     */
    BureauDAO bureauDAO = null;
    

    public creabur() {
        initComponents();
    }

    public void setBureauDAO(BureauDAO bureauDAO) {
        this.bureauDAO = bureauDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        creer = new javax.swing.JButton();
        lblid = new javax.swing.JLabel();
        txtidbur = new javax.swing.JTextField();
        lblsigle = new javax.swing.JLabel();
        lbltel = new javax.swing.JLabel();
        lbldesc = new javax.swing.JLabel();
        txtsigle = new javax.swing.JTextField();
        txttel = new javax.swing.JTextField();
        txtdesc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        vider = new javax.swing.JButton();

        creer.setText("Création");
        creer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerActionPerformed(evt);
            }
        });

        lblid.setText("Id du bureau");

        txtidbur.setEditable(false);
        txtidbur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidburActionPerformed(evt);
            }
        });

        lblsigle.setText("Sigle");

        lbltel.setText("Tel");

        lbldesc.setText("Description");

        txtsigle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsigleActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Création d'un bureau ");

        vider.setText("Vider");
        vider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblid)
                                    .addComponent(lblsigle)
                                    .addComponent(lbltel)
                                    .addComponent(lbldesc))
                                .addGap(45, 45, 45)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtidbur, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                                    .addComponent(txtsigle)
                                    .addComponent(txttel)
                                    .addComponent(txtdesc)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(creer)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(vider))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel1)))
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblid)
                    .addComponent(txtidbur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblsigle)
                    .addComponent(txtsigle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbltel)
                    .addComponent(txttel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbldesc))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creer)
                    .addComponent(vider))
                .addGap(27, 27, 27))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void creerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerActionPerformed
        // TODO add your handling code here:
        try {
            String sigle = txtsigle.getText();
            String tel = txttel.getText();
            String desc = txtdesc.getText();
            Bureau b1 = new Bureau(0, sigle, tel, desc);
            //System.out.println(b1);
            b1 = bureauDAO.create(b1);
            txtidbur.setText("" + b1.getIdbur());
            JOptionPane.showMessageDialog(this, "Bureau ajouté ", "succès", JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_creerActionPerformed

    private void txtidburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidburActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidburActionPerformed

    private void txtsigleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsigleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsigleActionPerformed

    private void viderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viderActionPerformed
        // TODO add your handling code here:
        txtidbur.setText("");
        txtsigle.setText("");
        txttel.setText("");
        txtdesc.setText("");
        
    }//GEN-LAST:event_viderActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton creer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbldesc;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblsigle;
    private javax.swing.JLabel lbltel;
    private javax.swing.JTextField txtdesc;
    private javax.swing.JTextField txtidbur;
    private javax.swing.JTextField txtsigle;
    private javax.swing.JTextField txttel;
    private javax.swing.JButton vider;
    // End of variables declaration//GEN-END:variables
}
