/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bureau.graph;

import bureau.DAO.BureauDAO;
import bureau.DAO.UtilisateurDAO;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import messages.metier.Bureau;
import messages.metier.Utilisateur;


/**
 *
 * @author USER
 */
public class creeremp extends javax.swing.JPanel {

    /**
     * Creates new form creeremp
     */
    public creeremp() {
        initComponents();

    }
    BureauDAO burDAO = null;
    Bureau b1 = null;
    UtilisateurDAO utilDAO = null;
    Utilisateur u1 = null;

    public void setBureauDAO(BureauDAO burDAO) {
        this.burDAO = burDAO;
    }

    public void setUtilisateurDAO(UtilisateurDAO utilDAO) {
        this.utilDAO = utilDAO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblnom = new javax.swing.JLabel();
        lblprenom = new javax.swing.JLabel();
        lblmatr = new javax.swing.JLabel();
        lblbur = new javax.swing.JLabel();
        txtprenom = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtmatr = new javax.swing.JTextField();
        valider = new javax.swing.JButton();
        txtsigle = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ajouter un employé");

        lblnom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblnom.setText("Nom");

        lblprenom.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblprenom.setText("Prenom");

        lblmatr.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblmatr.setText("Matricule");

        lblbur.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblbur.setText("Sigle du bureau");

        valider.setText("Ajouter");
        valider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                validerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblnom)
                            .addComponent(lblprenom)
                            .addComponent(lblmatr)
                            .addComponent(lblbur))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtmatr, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(txtnom, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtprenom)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(214, 214, 214)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(valider)
                                    .addGap(46, 46, 46)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(txtsigle, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblprenom)
                    .addComponent(txtprenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblnom)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmatr)
                    .addComponent(txtmatr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblbur)
                    .addComponent(txtsigle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(valider)
                .addContainerGap(115, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void validerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_validerActionPerformed
        // TODO add your handling code here:
        String prenom = txtprenom.getText();
        String nom = txtprenom.getText();
        String matr = txtmatr.getText();
        String sigle = txtsigle.getText();
        
        if (prenom.isEmpty()||nom.isEmpty()||sigle.isEmpty()||matr.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Veuillez remplir tous les champs", "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
        else {
        try {
            b1 = burDAO.rechsigle(sigle);
            int idbur = b1.getIdbur();
            u1 = new Utilisateur(0, matr, nom, prenom, idbur);
            try {
                u1 = utilDAO.create(u1);
                JOptionPane.showMessageDialog(this, "Employé ajouté ", "succès", JOptionPane.INFORMATION_MESSAGE);
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_validerActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblbur;
    private javax.swing.JLabel lblmatr;
    private javax.swing.JLabel lblnom;
    private javax.swing.JLabel lblprenom;
    private javax.swing.JTextField txtmatr;
    private javax.swing.JTextField txtnom;
    private javax.swing.JTextField txtprenom;
    private javax.swing.JTextField txtsigle;
    private javax.swing.JButton valider;
    // End of variables declaration//GEN-END:variables
}
