/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bureau.graph;

import java.awt.CardLayout;
import java.sql.Connection;
import javax.swing.JOptionPane;
import myconnections.DBConnection;
import bureau.DAO.BureauDAO;
import bureau.DAO.UtilisateurDAO;
import bureau.DAO.MessageDAO;
/**
 *
 * @author Valentin
 */
public class Gestion extends javax.swing.JFrame {

    /**
     * Creates new form Accueil
     */
    CardLayout cardl;

    public Gestion() {
        initComponents();
        cardl = (CardLayout) this.getContentPane().getLayout();
        Connection dbConnect = DBConnection.getConnection();
        if (dbConnect == null) {
            System.out.println("Connexion invalide");
            JOptionPane.showMessageDialog(this, "Connexion invalide", "ERREUR", JOptionPane.ERROR_MESSAGE);
        }

        BureauDAO bureauDAO = new BureauDAO();
        bureauDAO.setConnection(dbConnect);
        UtilisateurDAO utilDAO = new UtilisateurDAO();
        utilDAO.setConnection(dbConnect);
        MessageDAO messDAO = new MessageDAO();
        messDAO.setConnection(dbConnect);
        
        
        
        affenv1.setMessageDAO(messDAO);
        
        affrec1.setMessageDAO(messDAO);
        
        
        creabur1.setBureauDAO(bureauDAO);
        
        creeremp1.setBureauDAO(bureauDAO);
        creeremp1.setUtilisateurDAO(utilDAO);
        
        modifbur1.setBureauDAO(bureauDAO);
        
        modifemp1.setBureauDAO(bureauDAO);
        modifemp1.setUtilisateurDAO(utilDAO);
        
        
        rechdescbur1.setBureauDAO(bureauDAO);
        
        rechidbur1.setBureauDAO(bureauDAO);
        rechidbur1.setUtilisateurDAO(utilDAO);
                        
        suppbur1.setBureauDAO(bureauDAO);
        
        suppemp1.setBureauDAO(bureauDAO);
        suppemp1.setUtilisateurDAO(utilDAO);
        
        
        
        /*rechCliNum.setClientDAO(clientDAO);
        rechNom.setClientDAO(clientDAO);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        accueil1 = new bureau.graph.Accueil();
        affenv1 = new bureau.graph.affenv();
        affrec1 = new bureau.graph.affrec();
        creabur1 = new bureau.graph.creabur();
        creeremp1 = new bureau.graph.creeremp();
        modifbur1 = new bureau.graph.modifbur();
        modifemp1 = new bureau.graph.modifemp();
        rechdescbur1 = new bureau.graph.rechdescbur();
        rechemp1 = new bureau.graph.rechemp();
        rechidbur1 = new bureau.graph.rechidbur();
        suppbur1 = new bureau.graph.suppbur();
        suppemp1 = new bureau.graph.suppemp();
        menu = new javax.swing.JMenuBar();
        Bur = new javax.swing.JMenu();
        creerbur = new javax.swing.JMenuItem();
        modifbur = new javax.swing.JMenuItem();
        suppbur = new javax.swing.JMenuItem();
        rechbur = new javax.swing.JMenuItem();
        rechdescbur = new javax.swing.JMenuItem();
        Emp = new javax.swing.JMenu();
        creeremp = new javax.swing.JMenuItem();
        rechemp = new javax.swing.JMenuItem();
        modifemp = new javax.swing.JMenuItem();
        suppemp = new javax.swing.JMenuItem();
        affemp = new javax.swing.JMenuItem();
        Mess = new javax.swing.JMenu();
        affenv = new javax.swing.JMenuItem();
        affrecu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(621, 410));
        getContentPane().setLayout(new java.awt.CardLayout());
        getContentPane().add(accueil1, "card2");
        getContentPane().add(affenv1, "card3");
        getContentPane().add(affrec1, "card4");
        getContentPane().add(creabur1, "card5");
        getContentPane().add(creeremp1, "card6");
        getContentPane().add(modifbur1, "card7");
        getContentPane().add(modifemp1, "card8");
        getContentPane().add(rechdescbur1, "card9");
        getContentPane().add(rechemp1, "card10");
        getContentPane().add(rechidbur1, "card11");
        getContentPane().add(suppbur1, "card12");
        getContentPane().add(suppemp1, "card13");

        Bur.setText("Bureau");
        Bur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BurActionPerformed(evt);
            }
        });

        creerbur.setText("Nouveau");
        creerbur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerburActionPerformed(evt);
            }
        });
        Bur.add(creerbur);

        modifbur.setText("Modifier ");
        modifbur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifburActionPerformed(evt);
            }
        });
        Bur.add(modifbur);

        suppbur.setText("Suppression");
        suppbur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppburActionPerformed(evt);
            }
        });
        Bur.add(suppbur);

        rechbur.setText("Recherche id");
        rechbur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechburActionPerformed(evt);
            }
        });
        Bur.add(rechbur);

        rechdescbur.setText("Recherche description");
        rechdescbur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechdescburActionPerformed(evt);
            }
        });
        Bur.add(rechdescbur);

        menu.add(Bur);

        Emp.setText("Employés");

        creeremp.setText("Nouveau");
        creeremp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creerempActionPerformed(evt);
            }
        });
        Emp.add(creeremp);

        rechemp.setText("Recherche");
        rechemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechempActionPerformed(evt);
            }
        });
        Emp.add(rechemp);

        modifemp.setText("Modifier bureau");
        modifemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifempActionPerformed(evt);
            }
        });
        Emp.add(modifemp);

        suppemp.setText("Supprimer");
        suppemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppempActionPerformed(evt);
            }
        });
        Emp.add(suppemp);

        affemp.setText("Afficher par bureau");
        affemp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affempActionPerformed(evt);
            }
        });
        Emp.add(affemp);

        menu.add(Emp);

        Mess.setText("Messages");

        affenv.setText("Afficher envoyés");
        affenv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affenvActionPerformed(evt);
            }
        });
        Mess.add(affenv);

        affrecu.setText("Afficher reçus");
        affrecu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                affrecuActionPerformed(evt);
            }
        });
        Mess.add(affrecu);

        menu.add(Mess);

        setJMenuBar(menu);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void creerburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerburActionPerformed

        cardl.show(this.getContentPane(), "card5");
    }//GEN-LAST:event_creerburActionPerformed

    private void rechburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechburActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "card11");
    }//GEN-LAST:event_rechburActionPerformed

    private void rechdescburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechdescburActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "card9");
    }//GEN-LAST:event_rechdescburActionPerformed

    private void suppburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppburActionPerformed
        // TODO add your handling code here:   
        cardl.show(this.getContentPane(), "card12");
    }//GEN-LAST:event_suppburActionPerformed

    private void creerempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creerempActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "card6");
    }//GEN-LAST:event_creerempActionPerformed

    private void modifempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifempActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "card8");
    }//GEN-LAST:event_modifempActionPerformed

    private void suppempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppempActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "card13");
    }//GEN-LAST:event_suppempActionPerformed

    private void affempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affempActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "card11");
    }//GEN-LAST:event_affempActionPerformed

    private void affenvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affenvActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "card3");
    }//GEN-LAST:event_affenvActionPerformed

    private void affrecuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_affrecuActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "card4");
    }//GEN-LAST:event_affrecuActionPerformed

    private void rechempActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechempActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "card10");
    }//GEN-LAST:event_rechempActionPerformed

    private void BurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BurActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_BurActionPerformed

    private void modifburActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifburActionPerformed
        // TODO add your handling code here:
        cardl.show(this.getContentPane(), "card7");
    }//GEN-LAST:event_modifburActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Bur;
    private javax.swing.JMenu Emp;
    private javax.swing.JMenu Mess;
    private bureau.graph.Accueil accueil1;
    private javax.swing.JMenuItem affemp;
    private javax.swing.JMenuItem affenv;
    private bureau.graph.affenv affenv1;
    private bureau.graph.affrec affrec1;
    private javax.swing.JMenuItem affrecu;
    private bureau.graph.creabur creabur1;
    private javax.swing.JMenuItem creerbur;
    private javax.swing.JMenuItem creeremp;
    private bureau.graph.creeremp creeremp1;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenuItem modifbur;
    private bureau.graph.modifbur modifbur1;
    private javax.swing.JMenuItem modifemp;
    private bureau.graph.modifemp modifemp1;
    private javax.swing.JMenuItem rechbur;
    private javax.swing.JMenuItem rechdescbur;
    private bureau.graph.rechdescbur rechdescbur1;
    private javax.swing.JMenuItem rechemp;
    private bureau.graph.rechemp rechemp1;
    private bureau.graph.rechidbur rechidbur1;
    private javax.swing.JMenuItem suppbur;
    private bureau.graph.suppbur suppbur1;
    private javax.swing.JMenuItem suppemp;
    private bureau.graph.suppemp suppemp1;
    // End of variables declaration//GEN-END:variables
}
